services:
  app:
    build:
      context: ./backend
    container_name: zesty
    restart: unless-stopped
    env_file:
      - backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:9.3
    container_name: zesty-db
    restart: unless-stopped
    env_file:
      - db/.env
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./db/data.sql:/docker-entrypoint-initdb.d/data.sql:ro
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
